### ISSUE TITLE
Support RK3399?

### ISSUE THREAD

**Issue by BiatuAutMiahn** [linuxerwang/rkflashkit#10]
Can you add support for the Firefly-RK3399?

**Comment by linuxerwang** [comment]
What's its product ID?

**Comment by BiatuAutMiahn** [comment]
Where can I find that?

This is the product: [http://en.t-firefly.com/en/firenow/Firefly_RK3399/](http://en.t-firefly.com/en/firenow/Firefly_RK3399/)

**Comment by cdslashetc** [comment]
The Firefly team already made a fork with RK3399 support https://github.com/T-Firefly/rkflashkit you can find more information in the Flash Image section of the wiki http://wiki.t-firefly.com/index.php/Firefly-RK3399/en

**Comment by linuxerwang** [comment]
They can create a pull request and I'll be happy to merge it.

**Comment by cdslashetc** [comment]
Cool! I'll let them know.

**Comment by BiatuAutMiahn** [comment]
ya, that's why I made this issue

**Comment by linuxerwang** [comment]
The key is this line: https://github.com/linuxerwang/rkflashkit/blob/master/src/rkflashkit/rktalk.py#L28

Someone has to tell me the product ID for RK3399, since I don't have any such devices.

**Comment by BiatuAutMiahn** [comment]
well, as a LOADER device it is 0x330C

**Comment by linuxerwang** [comment]
Added with commit dd6829702abd2d195d9fe41648b08dcba683ba87.
