### ISSUE TITLE
Push a tag for 0.1.4

### ISSUE THREAD

**Issue by mrueg** [linuxerwang/rkflashkit#6]
Can you please push a tag for 0.1.4? Thanks

**Comment by linuxerwang** [comment]
Done.

Btw, I am going to transfer this project to someone who wants to own it since I am working on other stuff and have no time on rkflashkit.  Would you like to own it?

**Comment by mrueg** [comment]
@linuxerwang Sorry, I don't have time to maintain it. Maybe move it over to https://github.com/linux-rockchip or ask in #linux-rockchip on freenode if someone is interested. maybe @naobsd is interested?

**Comment by mrueg** [comment]
@linuxerwang https://github.com/linuxerwang/rkflashkit/tags doesn't show a tag. could you do a git push --tags

**Comment by linuxerwang** [comment]
Done this time.
