### ISSUE TITLE
support RK3229

### ISSUE THREAD

**Issue by CGarces** [linuxerwang/rkflashkit#7]
I have an Android TV with RK3229.

I can connect with adb without problems but `sudo rkflashkit part` not find my device.

How can I hep to add support for RK3229? 

The id is `0x320b`, as I see in the [rkflashtool](https://github.com/linux-rockchip/rkflashtool/blob/master/rkflashtool.c)

``` C
 { 0x320b, "RK322X" }, // Both RK3228 and RK3229
```

How can I provide information to support this SOC?

**Comment by linuxerwang** [comment]
Added. Please git pull.

**Comment by linuxerwang** [comment]
BTW, you must put the device in boot loader mode.
