### ISSUE TITLE
Please add this product ID

### ISSUE THREAD

**Issue by ggt** [linuxerwang/rkflashkit#9]
in -> /usr/share/rkflashkit/lib/rkflashkit/rktalk.py
in section : RK_PRODUCT_IDS = set([
 
0x292a, # rk2928sdk 

------
for info :

	Loading partition information
	MACHINE_MODEL:rk2928sdk
	MACHINE_ID:007
	MANUFACTURER:RK2928SDK
	MAGIC: 0x5041524B
	ATAG: 0x60000800
	MACHINE: 2928 
	CHECK_MASK: 0x80
	KERNEL_IMG: 0x60408000
	CMDLINE:console=ttyFIQ0 androidboot.console=ttyFIQ0 init=/init initrd=0x62000000,0x00800000 mtdparts=rk29xxnand:0x00001380@0x00000080(kernel),0x0000200@0x00001400(boot),0x0000400@0x00001600(userdata),0x00e600@0x00001a00(system),0x0000008@0x10000(backup)

**Comment by linuxerwang** [comment]
Fixed with a5c11af769fdedb5f681ea01474453ae91112c39.

**Comment by ggt** [comment]
Thanks man ;) it works like a charm ;)

Have a nice day :!

2016-12-29 17:59 GMT+01:00 linuxerwang <notifications@github.com>:
